id = "sintax-lang"
name = "Sintax"
version = "0.1.0"
schema_version = 1
authors = ["Eric Kweyunga <erickweyunga@gmail.com>"]
description = "Sintax language support — syntax highlighting, brackets, outline"
repository = "https://github.com/erickweyunga/sintax"

[grammars.sintax]
repository = "https://github.com/erickweyunga/tree-sitter-sintax"
rev = "f5a5736"
