name = "Sintax"
grammar = "sintax"
path_suffixes = ["sx"]
line_comments = ["-- "]
tab_size = 4
hard_tabs = false
first_line_pattern = "^(use |fn |>>)"

brackets = [
  { start = "(", end = ")", close = true, newline = false },
  { start = "[", end = "]", close = true, newline = false },
  { start = "{", end = "}", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
  { start = "'", end = "'", close = true, newline = false, not_in = ["string", "comment"] },
]
